### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by bagomot** [AlexanderZhirov/singlog#1]
Hello! Your library does not work on Windows due to the lack of an equivalent to syslog. Will the ability to work on Windows without syslog functionality be added to the library? Ideally, the Windows Event Log could be used.

**Comment by alexanderzhirov** [comment]
Hi! Yes, I want to refine this functionality later. Since I myself am developing specifically for Linux, I was unable to provide support for output to the Windows log.

**Comment by alexanderzhirov** [comment]
@bagomot You can try this update (Windows/Linux) `git clone -b dev https://git.zhirov.kz/dlang/singlog.git`:

```d
import singlog;

void main(string[] argv) {
    log.output(log.SYSLOG | log.STDOUT | log.FILE)
        .name(argv[0])
        .level(Log.DEBUGGING)
        .file("./test.log");
    log.e("hello!");
    log.w("hello!");
    log.i("hello!");
}
```
